### ISSUE TITLE
SSL23_GET_SERVER_HELLO:unknown protocol error during setup.py installation

### ISSUE THREAD

**Issue by chalapathyvenkata66** [clusto/clusto#81]
Hi,

I'm trying to install the clusto on my system, but the installation fails as it is unable to download items from 'http://pypi.python.org/simple/IPy/' site. Below is the snippet of the error message I get during the install.

Installed /usr/lib/python2.6/site-packages/clusto-0.7.9-py2.6.egg
Processing dependencies for clusto==0.7.9
Searching for IPy
Reading http://pypi.python.org/simple/IPy/
Download error: [Errno 1] _ssl.c:492: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol -- Some packages may not be found!
Reading http://pypi.python.org/simple/IPy/
Download error: [Errno 1] _ssl.c:492: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol -- Some packages may not be found!
Couldn't find index page for 'IPy' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
Download error: [Errno 1] _ssl.c:492: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol -- Some packages may not be found!
No local packages or download links found for IPy
error: Could not find suitable distribution for Requirement.parse('IPy')

Please note that my system is behind a corporate firewall and I'm using a proxy to reach the destination site. Any help is greatly appreciated.
Thanks.

**Comment by JeremyGrosser** [comment]
You're running an outdated SSL library that does not support TLS 1.2, which is required for connecting to PyPI as of June 30th. This is not a clusto specific issue.  

https://mail.python.org/pipermail/distutils-sig/2017-January/029970.html

**Comment by JeremyGrosser** [comment]
The output you pasted above shows you're running Python 2.6, which does not support TLS 1.2. Upgrade your Python.
